### ISSUE TITLE
Create ConnectionString Factory for Component Factories

### ISSUE THREAD

**Issue by bytemaster-0xff** [SumoSoftware/Sumo.Data#8]
Currently SqliteDataComponentFactory expense a string with connection string information.  In some cases this might not be a string literal but might need to identified by some other means (for example the connection string in iOS is different than Windows).  

The task here is to create an IConnectionStringProvider that will return the connection string via an implemented class. 

Also since SqliteDataComponentFactory requires a connection string, it means we can't use the IoC container to create an instance.

**Comment by marklauter** [comment]
implemented with f72c23d40145fd7bbb6c900bb3b787dc9c44afcd
